# This is a basic workflow to help you get started with Actions

name: Workflow to deploy ARM Templates to resource group

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build-and-deploy-to-dev:
    #name the job
    name: build-and-deploy-to-dev
    environment: dev
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: PowerShell script number 1
        # You may pin to the exact commit or the version.
        # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          # PowerShell script to execute in Actions-hydrated context
          script: |
            Write-Host "hello"      
        
      - shell: pwsh
        name: PowerShell Script number 2
        env:
         SUPER_SECRET: ${{ secrets.MTC_SECRET_1_DEV }}
        run: |
            Write-Host "$env:MTC_SECRET_1_DEV"
            
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
        
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
            
        
