# This is a basic workflow to help you get started with Actions

name: Workflow to deploy ARM Templates to resource group

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: TEST
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.MTC_SECRET_1 }}
        run: |
            example-command "$MTC_SECRET_1"
